version: '3.8'

services:
  memcached:
    image: 'memcached:alpine'

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '8001:8025'

  redis:
    image: 'redis:alpine'

  postgres:
    image: 'postgres:11.1-alpine'
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '8004:5432'

  php:
    container_name: php
    build:
      context: ./php
      args:
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_NAME=${ADMIN_NAME}
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/prettypost
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/prettypost
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  clickhouse:
    image: 'yandex/clickhouse-server:latest'